"""Add sub-subjects

Revision ID: 32a2fdfea9ab
Revises: f4c16390c865
Create Date: 2026-03-14 15:33:10.526188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a2fdfea9ab'
down_revision = 'f4c16390c865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False, server_default="1.0"))
        # batch_op.create_foreign_key('fk_subject_parent_id', 'subject', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_subject_parent_id', type_='foreignkey')
        batch_op.drop_column('weight')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
