"""add cascade delete to user_flashcard_star

Revision ID: 343372362e25
Revises: 6143c559d2ba
Create Date: 2025-12-20 00:54:31.665161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343372362e25'
down_revision = '6143c559d2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreating user_flashcard_star to add ON DELETE CASCADE
    op.drop_table('user_flashcard_star')
    op.create_table('user_flashcard_star',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('flashcard_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'flashcard_id')
    )

    # Skipping citation changes to avoid constraint naming issues for now
    # with op.batch_alter_table('citation', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_citation_group_id'), ['group_id'], unique=False)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('citation_group', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_citation_group_user_id'), ['user_id'], unique=False)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_flashcard_star')
    op.create_table('user_flashcard_star',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('flashcard_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('user_id', 'flashcard_id')
    )
    # ### end Alembic commands ###
