"""Reconcile models after merge

Revision ID: 4b82cb051471
Revises: ce83cb40063b
Create Date: 2026-01-24 02:30:50.184373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b82cb051471'
down_revision = 'ce83cb40063b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_semester')
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_group_id'), ['group_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_citation_group_id_citation_group', 'citation_group', ['group_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_group_user_id'), ['user_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_citation_group_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_flashcard_star', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_flashcard_star_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_flashcard_star_flashcard_id_flashcard', 'flashcard', ['flashcard_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_flashcard_star', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'flashcard', ['flashcard_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_user_id'))

    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_id'))

    op.create_table('_alembic_tmp_semester',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
