"""add share_token and user_flashcard_star

Revision ID: 6143c559d2ba
Revises: d340753c22bf
Create Date: 2025-12-20 00:08:06.948383

"""
from alembic import op
import sqlalchemy as sa
import secrets

# revision identifiers, used by Alembic.
revision = '6143c559d2ba'
down_revision = 'd340753c22bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    # connection.execute(sa.text("PRAGMA foreign_keys=OFF")) # Only needed for the fix

    op.create_table('user_flashcard_star',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'flashcard_id')
    )
    # with op.batch_alter_table('citation', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_citation_group_id'), ['group_id'], unique=False)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('citation_group', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_citation_group_user_id'), ['user_id'], unique=False)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=32), nullable=True))

    # Update existing rows with unique tokens
    # connection = op.get_bind() # Already got it above if needed, but let's be clean
    flashcard_set = sa.Table(
        'flashcard_set',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('share_token', sa.String(length=32))
    )
    
    # Fetch all IDs
    results = connection.execute(sa.select(flashcard_set.c.id)).fetchall()
    for row in results:
        token = secrets.token_urlsafe(12)
        connection.execute(
            flashcard_set.update().where(flashcard_set.c.id == row[0]).values(share_token=token)
        )

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.alter_column('share_token', nullable=False, existing_type=sa.String(length=32))
        batch_op.create_unique_constraint('uq_flashcard_set_share_token', ['share_token'])

    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_token')

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_user_id'))

    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_id'))

    op.drop_table('user_flashcard_star')
    # ### end Alembic commands ###
