"""Add is_current field to Semester

Revision ID: 77710e6b93d6
Revises: a3f54da3c776
Create Date: 2025-12-13 20:44:44.833336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77710e6b93d6'
down_revision = 'a3f54da3c776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable with default value for SQLite compatibility
    with op.batch_alter_table('semester', schema=None, recreate='never') as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    
    # Set default value for any existing rows
    op.execute("UPDATE semester SET is_current = false WHERE is_current IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
