"""add curriculum tables

Revision ID: 95c64d4b07dc
Revises: a2b91e9b3350
Create Date: 2026-01-09 10:56:09.397716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c64d4b07dc'
down_revision = 'a2b91e9b3350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['curriculum_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_sub_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.alter_column('formatted_citation',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.alter_column('formatted_citation',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('curriculum_sub_topic')
    op.drop_table('curriculum_topic')
    op.drop_table('curriculum_subject')
    # ### end Alembic commands ###
