"""Add starred to flashcards

Revision ID: a2b91e9b3350
Revises: 1546fefe852e
Create Date: 2025-12-17 14:46:52.424207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b91e9b3350'
down_revision = '1546fefe852e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_column('starred')
    # ### end Alembic commands ###
