"""Add CurriculumExercise

Revision ID: b0d8e63b4b99
Revises: d7cc0cbe63e3
Create Date: 2026-01-09 22:15:08.028428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d8e63b4b99'
down_revision = 'd7cc0cbe63e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('question_html', sa.Text(), nullable=False),
    sa.Column('solution_html', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['curriculum_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_flashcard_star')
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_group_id'), ['group_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_group_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_flashcard_set_share_token'), type_='unique')
        batch_op.drop_column('is_public')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_flashcard_set_share_token'), ['share_token'])

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_user_id'))

    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_id'))

    op.create_table('user_flashcard_star',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('flashcard_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'flashcard_id')
    )
    op.drop_table('curriculum_exercise')
    # ### end Alembic commands ###
