"""add position to todo item

Revision ID: c845075c1f00
Revises: a2b91e9b3350
Create Date: 2025-12-19 14:16:58.156112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c845075c1f00'
down_revision = 'a2b91e9b3350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
