"""Add citation tables

Revision ID: c9e8fdd23efd
Revises: 5250579e9a4a
Create Date: 2025-12-17 12:55:31.670179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e8fdd23efd'
down_revision = '5250579e9a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_group_user_id'), 'citation_group', ['user_id'], unique=False)
    
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('formatted_citation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['citation_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_group_id'), 'citation', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_group_id'), table_name='citation')
    op.drop_table('citation')
    op.drop_index(op.f('ix_citation_group_user_id'), table_name='citation_group')
    op.drop_table('citation_group')
    # ### end Alembic commands ###
