"""Add Exercise model

Revision ID: ce83cb40063b
Revises: 332e4d2a6ea3
Create Date: 2026-01-22 11:18:57.931881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce83cb40063b'
down_revision = '332e4d2a6ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['curriculum_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('curriculum_exercise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subtopic_id', sa.INTEGER(), nullable=False),
    sa.Column('question_html', sa.TEXT(), nullable=False),
    sa.Column('solution_html', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['curriculum_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise')
    # ### end Alembic commands ###
