"""add is_public to flashcard set

Revision ID: d340753c22bf
Revises: c845075c1f00
Create Date: 2025-12-19 23:50:28.998246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd340753c22bf'
down_revision = 'c845075c1f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_column('is_public')
    # ### end Alembic commands ###

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('citation_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_user_id'))

    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'citation_group', ['group_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_citation_group_id'))

    # ### end Alembic commands ###
