"""add admin and teacher flags

Revision ID: d7cc0cbe63e3
Revises: 95c64d4b07dc
Create Date: 2026-01-09 11:05:22.304733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cc0cbe63e3'
down_revision = '95c64d4b07dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_teacher')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
